version: "3.9"
services:
  nagapp:
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /photo/nag:/app/nag-images
    links:
      - mongo
  mongo:
    image: mongo:3.6
    restart: always
    volumes:
      - /data/db:/data/db
